{% set name = "itkwidgets" %}
{% set version = "0.17.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e361f4f7500d2d6bf053c38220cbf7ec05ca671f2b6e08a38b752b68c527862

build:
  number: 0
  skip: True  # [win32 or (win64 and py2k)]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - colorcet
    - itk >=5.0.0
    - ipydatawidgets >=3.2.0
    - ipywidgets >=7.4.0
    - ipympl
    - numpy
    - scipy
    - six
    - zstandard

test:
  imports:
    - itkwidgets

about:
  home: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Interactive Jupyter widgets to visualize images in 2D and 3D'
  doc_url: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets
  dev_url: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets

extra:
  recipe-maintainers:
    - hadim
    - thewtex
    - SylvainCorlay
