{% set name = "itkwidgets" %}
{% set version = "0.20.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d40a25b06fa061392c0ebdaf56133717429c8285da6efaeb561ca887a6353a82

build:
  number: 0
  skip: True  # [win32 or (win64 and py2k)]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - colorcet
    - itk >=5.0.0
    - ipydatawidgets >=4.0.1
    - ipywidgets >=7.5.0
    - ipympl
    - numpy
    - scipy
    - six
    - zstandard

test:
  imports:
    - itkwidgets

about:
  home: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets
  license: Apache 2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Interactive Jupyter widgets to visualize images in 2D and 3D'
  doc_url: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets
  dev_url: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets

extra:
  recipe-maintainers:
    - hadim
    - thewtex
    - SylvainCorlay
